org: carlosalith
service: api-web-scraping-sismos

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  # Timeout de 30 segundos, buena idea para scraping
  timeout: 30
  iam:
    # Aseg√∫rate que este rol tenga permisos para DynamoDB (PutItem, Scan, DeleteItem)
    role: arn:aws:iam::691600124431:role/LabRole

functions:
  scrape_sismos:
    handler: scrap_sismos.lambda_handler
    package:
      include:
        - ./** # Incluir todo el contenido del directorio
    events:
      - http:
          path: /scrape/sismos
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaSismos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaSismos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
